import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { signIn } from 'next-auth/react';
import background from '../../public/background.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Secret Santa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main } style={{ backgroundImage: `url(${background.src})` }}>
        <div className={styles.loginCard}>
          <h1 className=' font-sans text-2xl'>Welcome To Tecciance Secret Santa Click below to Login</h1>
          <button
            className={styles.actionButton}
            onClick={() => {
              signIn(
                'azure-ad',
                { callbackUrl: '/dashboard' },
                { prompt: 'login' },
              );
            }}
          >
            Let&apos;s Get you In
          </button>
        </div>
      </main>
    </>
  );
}
